CREATE DATABASE festivals;
use festivals;
select * from festivals;
CREATE TABLE festivals(id int,fest_name varchar(20),fest_year int,fest_month varchar(20),fest_day varchar(20),food varchar(20),region varchar(20),no_Of_Visitors int,sweet varchar(20),veg_special varchar(20),nonveg_special boolean,country varchar(20),state varchar(20),holiday boolean,worshipFor varchar(20),amount_spent int,no_Of_days int,Dresscode varchar(20),fetival_god_gender varchar(20),fest_religion varchar(20));
INSERT INTO festivals VALUES(1,"Raksha Bandhan",2022,'aug','friday','holige','south',10,'ladoo','bisibele bath',false,'India','karnataka',true,'lord balarama',2000,1,'kurta','Male','hindu');
INSERT INTO festivals VALUES(2,"Varamahalakshmi",2022,'aug','saturday','vangi bath','south',15,'rava ladoo','vangi bhath',false,'India','Karnataka',true,'lakshmi',2500,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(3,'Independence day',2022,'aug','friday','lemon rice','south',14,'rava ladoo','lemon rice',false,'India','Karnataka',true,'lakshmi',2100,1,'traditional','female','hindu');

INSERT INTO festivals VALUES(4,'Onam',2022,'aug','tuesday','pongal','south',12,'rava ladoo','pongal',false,'India','Karnataka',true,'mahabali',2200,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(5,'teachers day',2022,'sept','wednesday','vangi bath','south',10,'rava ladoo','vangi bath',false,'India','Karnataka',true,'saraswathi',2300,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(6,'ganesh chaturthi',2022,'sept','thursday','pulao','south',16,'rava ladoo','pulao',false,'India','Karnataka',true,'ganesha',2400,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(7,'navrathri',2022,'sept','friday','vangi bath','south',17,'rava ladoo','vangi bath',false,'India','Karnataka',true,'durga',2500,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(8,'sankranthi',2022,'jan','saturday','tomato rice','south',25,'rava ladoo','tomato rice',false,'India','Karnataka',true,'surya',2600,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(9,'new year',2022,'jan','sunday','kichdi','south',18,'rava ladoo','kichdi',false,'India','Karnataka',true,'lakshmi',2700,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(10,'republic day',2022,'jan','wednesday','fried rice','south',19,'rava ladoo','fried rice',false,'India','Karnataka',true,'lakshmi',2800,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(11,'saraswathi puja',2022,'feb','saturday','bindi rice','south',12,'rava ladoo','bindi rice',false,'India','Karnataka',true,'saraswathi',2900,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(12,'mahashivrathri',2022,'march','tuesday','vangi bath','south',11,'rava ladoo','vangi bath',false,'India','Karnataka',true,'shiva',2100,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(13,'holi',2022,'march','friday','bisibele bath','south',14,'rava ladoo','bisibele bath',false,'India','Karnataka',true,'krishna',1000,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(14,'ram navami',2022,'april','sunday','lemon rice','south',11,'rava ladoo','lemon rice',false,'India','Karnataka',true,'rama',1200,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(15,'ambedkar jayanti',2022,'april','thursday','ponal','south',19,'rava ladoo','pongal',false,'India','Karnataka',true,'lakshmi',1300,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(16,'ugadi',2022,'april','saturday','vangi bath','south',17,'rava ladoo','vangi bath',false,'India','Karnataka',true,'vishnu',1500,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(17,'hanuman jayanti',2022,'april','saturday','vangi bath','south',18,'rava ladoo','vangi bath',false,'India','Karnataka',true,'hanuman',1600,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(18,'akshaya tritiya',2022,'may','tuesday','vangi bath','south',19,'rava ladoo','vangi bath',false,'India','Karnataka',true,'vishnu',1700,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(19,'eid',2022,'july','thursday','vangi bath','south',20,'rava ladoo','vangi bath',false,'India','Karnataka',true,'allah',2500,1,'traditional','male','muslim');
INSERT INTO festivals VALUES(20,'guru purnima',2022,'july','wednesday','pulao','south',22,'rava ladoo','pulao',false,'India','Karnataka',true,'buddha',1800,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(21,'nag panchami',2022,'aug','tuesday','bisibele bath','south',10,'rava ladoo','bisibele bath',false,'India','Karnataka',true,'shesha nag',1900,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(22,'janmashtami',2022,'aug','tuesday','vangi bath','south',25,'rava ladoo','vangi bath',false,'India','Karnataka',true,'krishna',2000,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(23,'durga pooja',2022,'october','monday','rava ladoo','south',17,'rava ladoo','lemon rice',false,'India','Karnataka',true,'durga',4300,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(24,'dussehra',2022,'october','wednesday','khicdi','south',15,'rava ladoo','khichdi',false,'India','Karnataka',true,'durga',5000,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(25,'christmas',2022,'december','sunday','bhindi rice','south',13,'rava ladoo','bhindi rice',false,'India','Karnataka',true,'jesus',3400,1,'traditional','male','christian');
INSERT INTO festivals VALUES(26,'Diwali',2022,'october','friday','pulao','south',14,'rava ladoo','pulao',false,'India','Karnataka',true,'lakshmi',3200,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(27,'gandhi jayanti',2022,'october','sunday','fried rice','south',12,'rava ladoo','fried rice',false,'India','Karnataka',true,'gandhi',3600,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(28,'lakshmi puja',2022,'october','monday','tomato rice','south',13,'rava ladoo','tomato rice',false,'India','Karnataka',true,'lakshmi',3800,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(29,'durga puja',2022,'october','tuesday','vangi bath','south',14,'rava ladoo','vangi bath',false,'India','Karnataka',true,'durga',3900,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(30,'lohri',2022,'jan','thursday','lemon rice','south',16,'rava ladoo','lemon rice',false,'India','Karnataka',true,'surya',3300,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(31,'nag panchami',2022,'aug','tuesday','vangi bath','south',14,'rava ladoo','vangi bath',false,'India','Karnataka',true,'shesha nag',3600,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(32,'hartalika teej',2022,'aug','tuesday','tomato rice','south',14,'rava ladoo','tomato rice',false,'India','Karnataka',true,'parvathi',3700,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(33,'ananth chaturdashi',2022,'sept','friday','vangi bath','south',17,'rava ladoo','vangi bath',false,'India','Karnataka',true,'ganesha',3800,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(34,'gurupurab',2022,'nov','wednesday','rice bath','south',18,'rava ladoo','rice bath',false,'India','Karnataka',true,'guru nanak',4500,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(35,'gandhi jayanti',2022,'oct','saturday','vangi bath','south',19,'rava ladoo','vangi bath',false,'India','Karnataka',true,'gandhi',5400,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(36,'karwa chauth',2022,'oct','friday','lemon rice','south',16,'rava ladoo','lemon rice',false,'India','Karnataka',true,'lakshmi',1100,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(37,'govardhan puja',2022,'oct','thursday','pongal','south',13,'rava ladoo','pongal',false,'India','Karnataka',true,'krishna',1800,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(38,'bhai dhuj',2022,'oct','tuesday','bisibele bath','south',13,'rava ladoo','bisibele bath',false,'India','Karnataka',true,'lakshmi',1900,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(39,'chhath puja',2022,'oct','wednesday','pongal','south',12,'rava ladoo','pongal',false,'India','Karnataka',true,'surya',1700,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(40,'saraswathi',2022,'oct','sunday','bindi rice','south',10,'rava ladoo','bindi rice',false,'India','Karnataka',true,'saraswathi',1600,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(41,'durgashtami',2022,'oct','monday','vangi bath','south',17,'rava ladoo','vangi bath',false,'India','Karnataka',true,'durga',1400,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(42,'mahanavami',2022,'oct','tuesday','bisibele bath','south',16,'rava ladoo','bisibele bath',false,'India','Karnataka',true,'lakshmi',1300,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(43,'ayudh pooja',2022,'oct','wednesday','vangi bath','south',19,'rava ladoo','vangi bath',false,'India','Karnataka',true,'lakshmi',1800,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(44,'ayudh mela',2022,'oct','thursday','lemon rice','south',20,'rava ladoo','lemon rice',false,'India','Karnataka',true,'lakshmi',1900,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(45,'papankusha ekadashi',2022,'oct','thursday','vangi bath','south',14,'rava ladoo','vangi bath',false,'India','Karnataka',true,'Padmanabham',2200,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(46,'pradosh vrat',2022,'oct','friday','tomato rice','south',15,'rava ladoo','tomato rice',false,'India','Karnataka',true,'shiva',2800,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(47,'ram das jayanthi',2022,'oct','sunday','pulao','south',18,'rava ladoo','pulao',false,'India','Karnataka',true,'ram',2600,1,'traditional','male','hindu');
INSERT INTO festivals VALUES(48,'dhanteras',2022,'oct','saturday','rice bath','south',19,'rava ladoo','rice bath',false,'India','Karnataka',true,' Dhanvantari',2200,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(49,'kali puja',2022,'oct','monday','vangi bath','south',13,'rava ladoo','vangi bath',false,'India','Karnataka',true,'kali',2300,1,'traditional','female','hindu');
INSERT INTO festivals VALUES(50,'chandra darshan',2022,'oct','thursday','lemon rice','south',12,'rava ladoo','lemon rice',false,'India','Karnataka',true,'moon',2400,1,'traditional','male','hindu');
